import fs from 'fs-extra';
import path from 'path';
import Handlebars from 'handlebars';

export interface GeneratorOptions {
  projectType: string;
  outputDir: string;
  dryRun: boolean;
}

export class TemplateGenerator {
  constructor() {
    // Templates are inline for now, but this can be extended to load from files
  }

  async generate(options: GeneratorOptions): Promise<string[]> {
    const createdFiles: string[] = [];
    const templateContext = {
      projectType: options.projectType,
      timestamp: new Date().toISOString(),
    };

    // Define files to generate based on project type
    const files = this.getFilesForProjectType(options.projectType);

    for (const file of files) {
      const outputPath = path.join(options.outputDir, file.outputPath);
      
      if (options.dryRun) {
        createdFiles.push(outputPath);
        continue;
      }

      // Ensure directory exists
      await fs.ensureDir(path.dirname(outputPath));

      // Generate content
      const content = await this.renderTemplate(file.template, templateContext);
      
      // Write file
      await fs.writeFile(outputPath, content, 'utf-8');
      createdFiles.push(outputPath);
    }

    return createdFiles;
  }

  private getFilesForProjectType(projectType: string): Array<{ template: string; outputPath: string }> {
    const baseFiles = [
      { template: 'custom.yaml.hbs', outputPath: 'custom.yaml' },
      { template: 'agents.yaml.hbs', outputPath: 'agents.yaml' },
      { template: 'phases.yaml.hbs', outputPath: 'phases.yaml' },
      { template: 'workflows.yaml.hbs', outputPath: 'workflows.yaml' },
      { template: 'README.md.hbs', outputPath: 'README.md' },
    ];

    // Add project-type specific files
    switch (projectType) {
      case 'typescript-monorepo':
        return [
          ...baseFiles,
          { template: 'monorepo-agents.yaml.hbs', outputPath: 'agents-monorepo.yaml' },
        ];
      case 'nextjs':
        return [
          ...baseFiles,
          { template: 'nextjs-phases.yaml.hbs', outputPath: 'phases-nextjs.yaml' },
        ];
      case 'rust':
        return [
          ...baseFiles,
          { template: 'rust-phases.yaml.hbs', outputPath: 'phases-rust.yaml' },
        ];
      case 'python':
        return [
          ...baseFiles,
          { template: 'python-phases.yaml.hbs', outputPath: 'phases-python.yaml' },
        ];
      default:
        return baseFiles;
    }
  }

  private async renderTemplate(templateName: string, context: Record<string, unknown>): Promise<string> {
    // For now, return inline templates
    // In production, these would be loaded from .hbs files
    const templates: Record<string, string> = {
      'custom.yaml.hbs': this.getCustomYamlTemplate(),
      'agents.yaml.hbs': this.getAgentsYamlTemplate(),
      'phases.yaml.hbs': this.getPhasesYamlTemplate(),
      'workflows.yaml.hbs': this.getWorkflowsYamlTemplate(),
      'README.md.hbs': this.getReadmeTemplate(),
    };

    const template = templates[templateName];
    if (!template) {
      throw new Error(`Template not found: ${templateName}`);
    }

    const compiled = Handlebars.compile(template);
    return compiled(context);
  }

  private getCustomYamlTemplate(): string {
    return `# AO Custom Configuration
# Generated by ao-starter
# Project Type: {{projectType}}
# Generated: {{timestamp}}

# Custom settings for your project
custom:
  project_type: {{projectType}}
  
  # Scheduling configuration
  scheduling:
    # Run daemon every 30 seconds
    interval_secs: 30
    
    # Auto-run ready tasks
    auto_run_ready: true
    
    # Auto-merge completed PRs
    auto_merge: false
    
    # Auto-create PRs for completed work
    auto_pr: true
`;
  }

  private getAgentsYamlTemplate(): string {
    return `# AO Agents Configuration
# Generated by ao-starter
# Project Type: {{projectType}}
# Generated: {{timestamp}}

agents:
  # Primary implementation agent
  developer:
    role: Senior Software Engineer
    model: claude-3-opus
    capabilities:
      - code-implementation
      - refactoring
      - debugging
      - testing
    max_concurrent: 1
    
  # Code review agent
  reviewer:
    role: Code Reviewer
    model: claude-3-sonnet
    capabilities:
      - code-review
      - security-analysis
      - performance-review
    max_concurrent: 2
    
  # Documentation agent
  documenter:
    role: Technical Writer
    model: claude-3-sonnet
    capabilities:
      - documentation
      - readme-generation
      - api-docs
    max_concurrent: 1
    
  # QA agent
  tester:
    role: QA Engineer
    model: claude-3-sonnet
    capabilities:
      - test-writing
      - test-execution
      - e2e-testing
    max_concurrent: 1
`;
  }

  private getPhasesYamlTemplate(): string {
    return `# AO Phases Configuration
# Generated by ao-starter
# Project Type: {{projectType}}
# Generated: {{timestamp}}

phases:
  # Planning phase
  planning:
    agent: developer
    description: Analyze requirements and create implementation plan
    timeout_secs: 300
    outputs:
      - plan
      - design_decisions
      
  # Implementation phase
  implementation:
    agent: developer
    description: Implement the planned changes
    timeout_secs: 1800
    outputs:
      - code_changes
      - test_results
    depends_on:
      - planning
      
  # Code review phase
  review:
    agent: reviewer
    description: Review implemented code for quality and security
    timeout_secs: 600
    outputs:
      - review_comments
      - approval_status
    depends_on:
      - implementation
      
  # Testing phase
  testing:
    agent: tester
    description: Run tests and verify functionality
    timeout_secs: 600
    outputs:
      - test_results
      - coverage_report
    depends_on:
      - implementation
      
  # Documentation phase
  documentation:
    agent: documenter
    description: Update documentation for changes
    timeout_secs: 300
    outputs:
      - updated_docs
    depends_on:
      - implementation
`;
  }

  private getWorkflowsYamlTemplate(): string {
    return `# AO Workflows Configuration
# Generated by ao-starter
# Project Type: {{projectType}}
# Generated: {{timestamp}}

workflows:
  # Standard development workflow
  standard:
    description: Standard workflow for feature development
    phases:
      - planning
      - implementation
      - review
      - testing
      - documentation
    default: true
    
  # Quick fix workflow
  quickfix:
    description: Simplified workflow for bug fixes
    phases:
      - implementation
      - testing
      
  # Feature workflow with extended review
  feature:
    description: Extended workflow for new features
    phases:
      - planning
      - implementation
      - review
      - testing
      - documentation
      
  # Documentation-only workflow
  docs:
    description: Workflow for documentation updates
    phases:
      - documentation
`;
  }

  private getReadmeTemplate(): string {
    return `# AO Workflows

This directory contains AO (Agent Orchestrator) workflow configurations for this project.

## Generated by ao-starter

- **Project Type:** {{projectType}}
- **Generated:** {{timestamp}}

## Files

- \`custom.yaml\` - Custom configuration settings
- \`agents.yaml\` - Agent definitions and capabilities
- \`phases.yaml\` - Phase definitions for workflows
- \`workflows.yaml\` - Workflow compositions

## Getting Started

1. Review and customize the generated configuration files
2. Start the AO daemon:
   \`\`\`bash
   ao daemon start
   \`\`\`
3. View available tasks:
   \`\`\`bash
   ao task list
   \`\`\`
4. Create a new task:
   \`\`\`bash
   ao task create "Your task description"
   \`\`\`

## Resources

- [AO Documentation](https://github.com/launchapp-dev/ao-docs)
- [AO CLI](https://github.com/launchapp-dev/ao)
- [AO Skills](https://github.com/launchapp-dev/ao-skills)
`;
  }
}
